displayName: WebSphere Liberty MicroProfile® 
description: Eclipse MicroProfile® on Websphere Liberty
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: "../icon/Codewind_blue.svg"
projectType: "liberty"
language: "java"
