displayName: Go
description: Sample microservice for simple go app
tags: ["go", "docker"]
globalMemoryLimit: 2674Mi
icon: "https://ibm.box.com/shared/static/1f4rsxgkxy4p8ourz6kli9sora4s4idw.svg"
projectType: "docker"
language: "go"
