displayName: Swift
description: Sample for building a Swift microservice
tags: ["swift"]
globalMemoryLimit: 2674Mi
icon: "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/icon/Codewind_blue.svg"
projectType: "swift"
language: "swift"
