displayName: Swift
description: Sample for building a Swift microservice
tags: ["swift"]
globalMemoryLimit: 2674Mi
icon: "https://ibm.box.com/shared/static/1f4rsxgkxy4p8ourz6kli9sora4s4idw.svg"
projectType: "swift"
language: "swift"
