displayName: Spring Boot®
description: Spring Boot®
tags: ["Java", "Spring",]
globalMemoryLimit: 2674Mi
icon: "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/icon/Codewind_blue.svg"
projectType: "spring"
language: "java"
