displayName: Lagom Java
description: Sample for building Lagom Reactive microservice in Java
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: "https://ibm.box.com/shared/static/1f4rsxgkxy4p8ourz6kli9sora4s4idw.svg"
projectType: "docker"
language: "java"
