displayName: Lagom Java
description: Sample for building Lagom Reactive microservice in Java
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: "../icon/Codewind_blue.svg"
projectType: "docker"
language: "java"
