displayName: Node.js Express
description: Eclipse Codewind Node.js Express sample application
tags: ["Nodejs"]
globalMemoryLimit: 2674Mi
icon: "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/icon/Codewind_blue.svg"
projectType: "nodejs"
language: "nodejs"
