displayName: Node.js Express
description: Eclipse Codewind Node.js Express sample application
tags: ["Nodejs"]
globalMemoryLimit: 2674Mi
icon: "../icon/Codewind_blue.svg"
projectType: "nodejs"
language: "nodejs"
