displayName: Node.js Express
description: Eclipse Codewind Node.js Express sample application
tags: ["Nodejs"]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "nodejs"
language: "nodejs"
