displayName: Open Liberty
description: Template for building an Open Liberty microservice in Java
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: "https://raw.githubusercontent.com/codewind-resources/codewind-templates/master/devfiles/icon/Codewind_blue.svg"
projectType: "docker"
language: "java"
