displayName: Open Liberty
description: Template for building an Open Liberty microservice in Java
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: "../icon/Codewind_blue.svg"
projectType: "docker"
language: "java"
