displayName: Python
description: HelloWorld microservice written in python
tags: ["python", "docker"]
globalMemoryLimit: 2674Mi
icon: "../icon/Codewind_blue.svg"
projectType: "docker"
language: "python"
